### ISSUE TITLE
Merging with EdyJ FBX exporter for Unity (fixing transforms)

### ISSUE THREAD

**Issue by Gradir** [A-Ribeiro/CustomBlenderFBXExporter#2]
Hey, I was wondering if you're familiar with
https://github.com/EdyJ/blender-to-unity-fbx-exporter

I'm using this exporter by default, but I'm not sure if it's maintened. Would it be possible to merge your exporter with it?
Cheers

**Comment by A-Ribeiro** [comment]
Hi,

Probably the structure of the code is different... It is not an easy task to merge two so different codes.
Maybe you can try the blender`s default exporter this code is based on.

best regards.
