### ISSUE TITLE
Doesn't seem to work past 4.0?

### ISSUE THREAD

**Issue by kirill-buzmakov-col** [A-Ribeiro/CustomBlenderFBXExporter#8]
Doesn't seem to work post 4.0. Since there was a specific 4.1.1 release I upgraded to 4.1.1 but no effect.
The addon installs normally and there's the additional export option
![fbx export option exists](https://github.com/A-Ribeiro/CustomBlenderFBXExporter/assets/91896892/78e98ec2-7a7f-49db-b104-18d740974f58)

but unlike in the past, there's no option to "remove armature" in the export settings:

![export settings - no "remove armature" option](https://github.com/A-Ribeiro/CustomBlenderFBXExporter/assets/91896892/5d4ba371-6230-4ba4-8981-8efeb1d0bbdd)

And finally, the resulting fbx file itself still has  the Armature node, AND the word "Armature" is still appended to every animation.

Prior to 4.0 the addon worked properly. The .py fbx export file in the "roaming" addons folder does contain the modified lines (commented with "Alessandro").

P.S. thank you very much for this addon, as I said in the past it was a huge help to deal with the annoying addition of Armature everywhere.

**Comment by A-Ribeiro** [comment]
Hi,

Can you check out the 'Armature' option in the exporter?

![image](https://github.com/A-Ribeiro/CustomBlenderFBXExporter/assets/24552820/1d671935-16ee-4e8d-9167-39609d0bbdd0)

**Comment by kirill-buzmakov-col** [comment]
Really sorry, didn't notice that one... will give it a try

**Comment by kirill-buzmakov-col** [comment]
Thanks, it worked! Now the only issue remains that the rigged model imported via this method is rotated in Unity 90 degrees, while it's normal when using the default FBX export. Do you have any idea why that might be happening?

**Comment by A-Ribeiro** [comment]
Have you tried changing the transform configuration through the exporter?

![image](https://github.com/A-Ribeiro/CustomBlenderFBXExporter/assets/24552820/3b465e21-fafe-4b3f-8dda-9d529a86493e)

**Comment by kirill-buzmakov-col** [comment]
Yes, I have, various configs. What's especially weird is that the exact same settings (for example, the exact default ones that are shown in the screenshot above) produce a different effect when used with the default exporter and yours.

**Comment by kirill-buzmakov-col** [comment]
Alright I seem to have found the setting that output the same mesh (rotation and scale-wise) in Unity:
![2024-07-07 19-06-24](https://github.com/A-Ribeiro/CustomBlenderFBXExporter/assets/91896892/d4372d55-41cd-480d-b1da-a48757ca80e5)
Thanks!!!
